```plantuml
@startuml

!define AWSPUML https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist

skinparam {
    DefaultFontColor #333
    DefaultFontName Arial

    ObjectBorderColor #007BFF
    ObjectBackgroundColor #D9E6F2

    ClassBackgroundColor #FFD580
    ClassBorderColor #FFA726
}

package "Event Processing" {
    cloud "Event Flows" {
        database "Object Storage" {
            [events store] #FFD580
        }

        queue "event queue" #D9E6F2

        frame "Event Workers" {
            [worker1] #FFD580
            [worker2] #FFD580
            [worker3] #FFD580
        }
    }

    [producer1] #D9E6F2
    [producer2] #D9E6F2
    [producer3] #D9E6F2
}

[producer1] --> queue
[producer2] --> queue
[producer3] --> queue
queue --> [worker1]
queue --> [worker2]
queue --> [worker3]
[worker1] --> [events store]
[worker2] --> [events store]
[worker3] --> [events store]

@enduml
```